# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=250)),
                ('rating', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='game_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=250)),
                ('rating', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='movie_pics')),
            ],
        ),
    ]
